# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-21 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodapp', '0003_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='health',
            name='hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.Neighbourhood'),
        ),
        migrations.AddField(
            model_name='health',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
